server:
  port: ${PORT:${SERVER_PORT:0}}
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: ms-usuarios
<<<<<<< HEAD:api-vakita/ms-usuarios/target/classes/application.yml
=======
# TO SEND MAIL
  mail:
    host: smtp.gmail.com
    port: 587
    username: vakitas.grupo3@gmail.com
    password: xkzmuhogqoxrihxt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
>>>>>>> 3d5211bc10a45f3e27bf8a4146e185a8635e403d:api-vakita/ms-usuarios/src/main/resources/application.yml
#  zipkin:
#    baseUrl: http://localhost:9411/
#    enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
<<<<<<< HEAD:api-vakita/ms-usuarios/target/classes/application.yml
    url: jdbc:mysql://localhost:3306/usersdb
    createDatabaseIfNotExist: true
=======
    url: jdbc:mysql://localhost:3306/usersdb?createDatabaseIfNotExist=true
>>>>>>> 3d5211bc10a45f3e27bf8a4146e185a8635e403d:api-vakita/ms-usuarios/src/main/resources/application.yml
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

<<<<<<< HEAD:api-vakita/ms-usuarios/target/classes/application.yml
=======

>>>>>>> 3d5211bc10a45f3e27bf8a4146e185a8635e403d:api-vakita/ms-usuarios/src/main/resources/application.yml
#Inicializacion de data en la bd, toma el script que está en resources al iniciar el ms
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceURL:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
    app:
      name: ms-usuarios
      version: 1.0.0
<<<<<<< HEAD:api-vakita/ms-usuarios/target/classes/application.yml
      description: Microservicios Usuarios
=======
      description: Microservicios Usuarios

spring-doc:
  api-docs:
    path: /swagger-usuarios
>>>>>>> 3d5211bc10a45f3e27bf8a4146e185a8635e403d:api-vakita/ms-usuarios/src/main/resources/application.yml
