variables:

  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
  - build
  - test
  - package

#  - deploy

cache:
  paths:
    - .m2/repository
    - target

# Build para todos los ms
build_usuarios:
  stage: build
  only:
    - backend
  script:
    - echo "Maven compile started on users"
    - cd ./api-vakita/ms-usuarios 
    - mvn compile

build_payment:
  stage: build
  only:
    - backend
  script:
    - echo "Maven compile started on payment"
    - cd ./api-vakita/ms-payment
    - mvn compile

build_vakitas:
  stage: build
  only:
    - backend
  script:
    - echo "Maven compile started on vakitas"
    - cd ./api-vakita/ms-vakitas
    - mvn compile

build_gateway:
  stage: build
  only:
    - backend
  script:
    - echo "Maven compile started on gateway"
    - cd ./api-vakita/gateway
    - mvn compile

build_eureka:
  stage: build
  only:
    - backend
  script:
    - echo "Maven compile started on eureka-server"
    - cd ./api-vakita/EurekaServer 
    - mvn compile

# Testeo para los resource server
test_usuarios:
 stage: test
 only:
    - backend
 script:
   - echo "Maven test started on users"
   - cd ./api-vakita/ms-usuarios
   - mvn clean test

test_vakitas:
 stage: test
 only:
    - backend
 script:
   - echo "Maven test started on vakitas"
   - cd ./api-vakita/ms-vakitas
   - mvn clean test

#Artefactos para los resource server
package_users: 
  stage: package
  only:
    - backend
  artifacts:
    paths:
    - api-vakita/ms-usuarios/target/*.jar
  script:
    - echo "Maven package started on usuarios"
    - cd ./api-vakita/ms-usuarios
    - mvn package

package_payment: 
  stage: package
  only:
    - backend
  artifacts:
    paths:
    - api-vakita/ms-payment/target/*.jar
  script:
    - echo "Maven package started on payment"
    - cd ./api-vakita/ms-payment
    - mvn package

package_vakitas: 
  stage: package
  only:
    - backend
  artifacts:
    paths:
    - api-vakita/ms-vakitas/target/*.jar
  script:
    - echo "Maven package started on vakitas"
    - cd ./api-vakita/ms-vakitas
    - mvn package