variables:

  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository
    - target

dummy_job:
  stage: build
  only:
    - config-server
  script: 
    - echo "Dummy job for lag-pipeline when has no tasks"
    - pwd 


# Build para todos los ms
build_usuarios:
  stage: build
  only:
    refs:
      - backend
    changes:
      - api-vakita/ms-usuarios/**/*
  script:
    - echo "Maven compile started on users"
    - cd ./api-vakita/ms-usuarios 
    - mvn compile

build_payment:
  stage: build
  only:
    refs:
      - backend
    changes:
      - api-vakita/ms-payment/**/*
  script:
    - echo "Maven compile started on payment"
    - cd ./api-vakita/ms-payment
    - mvn compile

build_vakitas:
  stage: build
  only:
    refs:
      - backend
    changes:
      - api-vakita/ms-vakitas/**/*
  script:
    - echo "Maven compile started on vakitas"
    - cd ./api-vakita/ms-vakitas
    - mvn compile

build_gateway:
  stage: build
  only:
    refs:
      - backend
    changes:
      - api-vakita/gateway/**/*
  script:
    - echo "Maven compile started on gateway"
    - cd ./api-vakita/gateway
    - mvn compile

build_eureka:
  stage: build
  only:
    refs:
      - backend
    changes:
      - api-vakita/EurekaServer/**/*
  script:
    - echo "Maven compile started on eureka-server"
    - cd ./api-vakita/EurekaServer 
    - mvn compile

# Testeo para los resource server
test_usuarios:
 stage: test
 only:
    refs:
      - backend
    changes:
      - api-vakita/ms-usuarios/**/*
 script:
   - echo "Maven test started on users"
   - cd ./api-vakita/ms-usuarios
   - mvn clean test

test_vakitas:
 stage: test
 only:
    refs:
      - backend
    changes:
      - api-vakita/ms-vakitas/**/*
 script:
   - echo "Maven test started on vakitas"
   - cd ./api-vakita/ms-vakitas
   - mvn clean test



