server:
  port: ${PORT:8761}

spring:
  application:
    name: eurekaServer
eureka:
  instance:
    hostname: eureka-server-container
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/