version: '3.9'
services:
  rabbitmq-container:
    image: rabbitmq:3.9-management
    container_name: rabbit-container
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 15672
      - 5672