server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-usuarios
          uri: http://18.207.194.96:9090/
          predicates:
            - Path=/api/v1/usuarios/**,/swagger-ui/**,/swagger-resources/**,/swagger-ui.html,/v3/api-docs,/webjars/**,/view/**,/swagger-usuarios

        - id: ms-payment
          uri: http://54.159.202.105:9090/
          predicates:
            - Path=/api/v1/payment/**,/swagger-ui/**,/swagger-resources/**,/swagger-ui.html,/v3/api-docs,/webjars/**,/view/**,/swagger-payment
          filters:
            - AuthenticationFilter

        - id: ms-vakitas
          uri: http://52.90.211.151:9090/
          predicates:
            - Path=/api/v1/vakita/**,/swagger-ui/**,/swagger-resources/**,/swagger-ui.html,/v3/api-docs,/webjars/**,/view/**,/swagger-vakitas
          filters:
            - AuthenticationFilter


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://107.22.65.36:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        #        include: "*"
        include: gateway
  info:
    env:
      enabled: true
    app:
      name: gateway
      version: 1.0.0
      description: Entry point

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"

info:
  app:
    name: ${spring.application.name}

