server:
  port: ${PORT:${SERVER_PORT:9090}}

spring:
  application:
    name: ms-payment

  data:
    mongodb:
      database: admin
      port: 27017
      host: 3.90.249.195
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceURL:
      defaultZone: http://107.22.65.36:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
    app:
      name: ms-payment
      version: 1.0.0
      description: Microservicios de Pagos

spring-doc:
  api-docs:
    path: /swagger-payment
#ESTO ES UN CAMBIO PARA PROBAR EL PIPELINE


