server:
  port: ${PORT:${SERVER_PORT:9090}}
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: ms-usuarios
# TO SEND MAIL
  mail:
    host: smtp.gmail.com
    port: 587
    username: vakitas.grupo3@gmail.com
    password: xkzmuhogqoxrihxt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    username: guest
    password: guest
    host: http://54.152.71.174
    port: 5672
  datasource:
    #    driverClassName: com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db.ctd.academy:3306/0723TDPI2N1C01LAED1021FT_GRUPO3?createDatabaseIfNotExist=true
    username: 0723TDPI2N1C01LAED1021FT_GRUPO3
    password: ahjoh5Lu
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


#Inicializacion de data en la bd, toma el script que está en resources al iniciar el ms
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceURL:
      defaultZone: http://107.22.65.36:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
    app:
      name: ms-usuarios
      version: 1.0.0
      description: Microservicios Usuarios