server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@gitlab.com:mcabate/ctd/hispanos/proyecto-integrador-2/proyecto-integrador-0723/1021ft-c1/equipo-03.git
          default-label: backend
          force-pull: true
          search-paths: ConfigData
